P8105 Homework 6
================
Junxian Chen (jc5314)
11/15/2019

# Problem 1

Firstly, read in the dataset and do data manipulation.

``` r
birthweight_dat = 
  read_csv("./data/birthweight.csv") %>% 
  mutate(
    babysex = factor(babysex, levels = c('1', '2')),
    frace = factor(frace, levels = c('1', '2', '3', '4', '8', '9')),
    malform = factor(malform, levels = c('0', '1')),
    mrace = factor(mrace, levels = c('1', '2', '3', '4', '8'))
  )
```

Use the **stepwise regreession method** to do the model selection.

``` r
model_fit = lm(bwt ~ ., data = birthweight_dat) %>% 
  step(direction = 'backward')
```

    ## Start:  AIC=48717.83
    ## bwt ~ babysex + bhead + blength + delwt + fincome + frace + gaweeks + 
    ##     malform + menarche + mheight + momage + mrace + parity + 
    ##     pnumlbw + pnumsga + ppbmi + ppwt + smoken + wtgain
    ## 
    ## 
    ## Step:  AIC=48717.83
    ## bwt ~ babysex + bhead + blength + delwt + fincome + frace + gaweeks + 
    ##     malform + menarche + mheight + momage + mrace + parity + 
    ##     pnumlbw + pnumsga + ppbmi + ppwt + smoken
    ## 
    ## 
    ## Step:  AIC=48717.83
    ## bwt ~ babysex + bhead + blength + delwt + fincome + frace + gaweeks + 
    ##     malform + menarche + mheight + momage + mrace + parity + 
    ##     pnumlbw + ppbmi + ppwt + smoken
    ## 
    ## 
    ## Step:  AIC=48717.83
    ## bwt ~ babysex + bhead + blength + delwt + fincome + frace + gaweeks + 
    ##     malform + menarche + mheight + momage + mrace + parity + 
    ##     ppbmi + ppwt + smoken
    ## 
    ##            Df Sum of Sq       RSS   AIC
    ## - frace     4    124365 320848704 48712
    ## - malform   1      1419 320725757 48716
    ## - ppbmi     1      6346 320730684 48716
    ## - momage    1     28661 320752999 48716
    ## - mheight   1     66886 320791224 48717
    ## - menarche  1    111679 320836018 48717
    ## - ppwt      1    131132 320855470 48718
    ## <none>                  320724338 48718
    ## - fincome   1    193454 320917792 48718
    ## - parity    1    413584 321137922 48721
    ## - mrace     3    868321 321592659 48724
    ## - babysex   1    853796 321578134 48727
    ## - gaweeks   1   4611823 325336161 48778
    ## - smoken    1   5076393 325800732 48784
    ## - delwt     1   8008891 328733230 48823
    ## - blength   1 102050296 422774634 49915
    ## - bhead     1 106535716 427260054 49961
    ## 
    ## Step:  AIC=48711.51
    ## bwt ~ babysex + bhead + blength + delwt + fincome + gaweeks + 
    ##     malform + menarche + mheight + momage + mrace + parity + 
    ##     ppbmi + ppwt + smoken
    ## 
    ##            Df Sum of Sq       RSS   AIC
    ## - malform   1      1447 320850151 48710
    ## - ppbmi     1      6975 320855679 48710
    ## - momage    1     28379 320877083 48710
    ## - mheight   1     69502 320918206 48710
    ## - menarche  1    115708 320964411 48711
    ## - ppwt      1    133961 320982665 48711
    ## <none>                  320848704 48712
    ## - fincome   1    194405 321043108 48712
    ## - parity    1    414687 321263390 48715
    ## - babysex   1    852133 321700837 48721
    ## - gaweeks   1   4625208 325473911 48772
    ## - smoken    1   5036389 325885093 48777
    ## - delwt     1   8013099 328861802 48817
    ## - mrace     3  13540415 334389119 48885
    ## - blength   1 101995688 422844392 49908
    ## - bhead     1 106662962 427511666 49956
    ## 
    ## Step:  AIC=48709.53
    ## bwt ~ babysex + bhead + blength + delwt + fincome + gaweeks + 
    ##     menarche + mheight + momage + mrace + parity + ppbmi + ppwt + 
    ##     smoken
    ## 
    ##            Df Sum of Sq       RSS   AIC
    ## - ppbmi     1      6928 320857079 48708
    ## - momage    1     28660 320878811 48708
    ## - mheight   1     69320 320919470 48708
    ## - menarche  1    116027 320966177 48709
    ## - ppwt      1    133894 320984044 48709
    ## <none>                  320850151 48710
    ## - fincome   1    193784 321043934 48710
    ## - parity    1    414482 321264633 48713
    ## - babysex   1    851279 321701430 48719
    ## - gaweeks   1   4624003 325474154 48770
    ## - smoken    1   5035195 325885346 48775
    ## - delwt     1   8029079 328879230 48815
    ## - mrace     3  13553320 334403471 48883
    ## - blength   1 102009225 422859375 49906
    ## - bhead     1 106675331 427525481 49954
    ## 
    ## Step:  AIC=48707.63
    ## bwt ~ babysex + bhead + blength + delwt + fincome + gaweeks + 
    ##     menarche + mheight + momage + mrace + parity + ppwt + smoken
    ## 
    ##            Df Sum of Sq       RSS   AIC
    ## - momage    1     29211 320886290 48706
    ## - menarche  1    117635 320974714 48707
    ## <none>                  320857079 48708
    ## - fincome   1    195199 321052278 48708
    ## - parity    1    412984 321270064 48711
    ## - babysex   1    850020 321707099 48717
    ## - mheight   1   1078673 321935752 48720
    ## - ppwt      1   2934023 323791103 48745
    ## - gaweeks   1   4621504 325478583 48768
    ## - smoken    1   5039368 325896447 48773
    ## - delwt     1   8024939 328882018 48813
    ## - mrace     3  13551444 334408523 48881
    ## - blength   1 102018559 422875638 49904
    ## - bhead     1 106821342 427678421 49953
    ## 
    ## Step:  AIC=48706.02
    ## bwt ~ babysex + bhead + blength + delwt + fincome + gaweeks + 
    ##     menarche + mheight + mrace + parity + ppwt + smoken
    ## 
    ##            Df Sum of Sq       RSS   AIC
    ## - menarche  1    100121 320986412 48705
    ## <none>                  320886290 48706
    ## - fincome   1    240800 321127090 48707
    ## - parity    1    431433 321317724 48710
    ## - babysex   1    841278 321727568 48715
    ## - mheight   1   1076739 321963029 48719
    ## - ppwt      1   2913653 323799943 48743
    ## - gaweeks   1   4676469 325562760 48767
    ## - smoken    1   5045104 325931394 48772
    ## - delwt     1   8000672 328886962 48811
    ## - mrace     3  14667730 335554021 48894
    ## - blength   1 101990556 422876847 49902
    ## - bhead     1 106864308 427750598 49952
    ## 
    ## Step:  AIC=48705.38
    ## bwt ~ babysex + bhead + blength + delwt + fincome + gaweeks + 
    ##     mheight + mrace + parity + ppwt + smoken
    ## 
    ##           Df Sum of Sq       RSS   AIC
    ## <none>                 320986412 48705
    ## - fincome  1    245637 321232048 48707
    ## - parity   1    422770 321409181 48709
    ## - babysex  1    846134 321832545 48715
    ## - mheight  1   1012240 321998651 48717
    ## - ppwt     1   2907049 323893461 48743
    ## - gaweeks  1   4662501 325648912 48766
    ## - smoken   1   5073849 326060260 48771
    ## - delwt    1   8137459 329123871 48812
    ## - mrace    3  14683609 335670021 48894
    ## - blength  1 102191779 423178191 49903
    ## - bhead    1 106779754 427766166 49950

``` r
summary(model_fit)
```

    ## 
    ## Call:
    ## lm(formula = bwt ~ babysex + bhead + blength + delwt + fincome + 
    ##     gaweeks + mheight + mrace + parity + ppwt + smoken, data = birthweight_dat)
    ## 
    ## Residuals:
    ##      Min       1Q   Median       3Q      Max 
    ## -1097.18  -185.52    -3.39   174.14  2353.44 
    ## 
    ## Coefficients:
    ##               Estimate Std. Error t value Pr(>|t|)    
    ## (Intercept) -6098.8219   137.5463 -44.340  < 2e-16 ***
    ## babysex2       28.5580     8.4549   3.378 0.000737 ***
    ## bhead         130.7770     3.4466  37.944  < 2e-16 ***
    ## blength        74.9471     2.0190  37.120  < 2e-16 ***
    ## delwt           4.1067     0.3921  10.475  < 2e-16 ***
    ## fincome         0.3180     0.1747   1.820 0.068844 .  
    ## gaweeks        11.5925     1.4621   7.929 2.79e-15 ***
    ## mheight         6.5940     1.7849   3.694 0.000223 ***
    ## mrace2       -138.7925     9.9071 -14.009  < 2e-16 ***
    ## mrace3        -74.8868    42.3146  -1.770 0.076837 .  
    ## mrace4       -100.6781    19.3247  -5.210 1.98e-07 ***
    ## parity         96.3047    40.3362   2.388 0.017004 *  
    ## ppwt           -2.6756     0.4274  -6.261 4.20e-10 ***
    ## smoken         -4.8434     0.5856  -8.271  < 2e-16 ***
    ## ---
    ## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
    ## 
    ## Residual standard error: 272.3 on 4328 degrees of freedom
    ## Multiple R-squared:  0.7181, Adjusted R-squared:  0.7173 
    ## F-statistic: 848.1 on 13 and 4328 DF,  p-value: < 2.2e-16

**Description of modeling process:** The model was selected by using the
stepwise regression method with backward elimination. The process
started with all candidate variables included and tested each variable
using a chosen model fit criterion. Then, variable whose loss gave the
most statistically insignificant deterioration of the model fit was
deleted. This process was repeated until no further variables can be
deleted without a statistically significant loss of fit.

A plot showing model residuals against fitted values:

``` r
birthweight_dat %>% 
  add_predictions(model_fit) %>% 
  add_residuals(model_fit) %>% 
  ggplot(aes(x = pred, y = resid)) +
  geom_point(alpha = .4, size = 2) +
  xlab("Fitted Values") +
  ylab("Residuals")
```

<img src="p8105_hw6_jc5314_files/figure-gfm/unnamed-chunk-4-1.png" width="90%" />

**Comment:** The residuals were mostly centered around 0 but with some
outliers on small fitted values.

Model using length at birth and gestational age as predictors (main
effects only):

``` r
model_fit2 = lm(bwt ~ blength + gaweeks, data = birthweight_dat)

model_fit2 %>% broom::tidy() %>% knitr::kable()
```

| term        |     estimate | std.error |  statistic | p.value |
| :---------- | -----------: | --------: | ---------: | ------: |
| (Intercept) | \-4347.66707 | 97.958360 | \-44.38281 |       0 |
| blength     |    128.55569 |  1.989891 |   64.60439 |       0 |
| gaweeks     |     27.04673 |  1.717930 |   15.74379 |       0 |

Model using head circumference, length, sex, and all interactions
(including the three-way interaction) between these:

``` r
model_fit3 = lm(bwt ~ bhead * blength * babysex, data = birthweight_dat)

model_fit3 %>% broom::tidy() %>% knitr::kable()
```

| term                   |       estimate |    std.error |   statistic |   p.value |
| :--------------------- | -------------: | -----------: | ----------: | --------: |
| (Intercept)            | \-7176.8170221 | 1264.8397394 | \-5.6740920 | 0.0000000 |
| bhead                  |    181.7956350 |   38.0542051 |   4.7772811 | 0.0000018 |
| blength                |    102.1269235 |   26.2118095 |   3.8962180 | 0.0000992 |
| babysex2               |   6374.8683508 | 1677.7669213 |   3.7996150 | 0.0001469 |
| bhead:blength          |    \-0.5536096 |    0.7802092 | \-0.7095656 | 0.4780117 |
| bhead:babysex2         |  \-198.3931810 |   51.0916850 | \-3.8830816 | 0.0001047 |
| blength:babysex2       |  \-123.7728875 |   35.1185360 | \-3.5244319 | 0.0004288 |
| bhead:blength:babysex2 |      3.8780531 |    1.0566296 |   3.6702106 | 0.0002453 |

Make comparisons in terms of the cross-validated prediction error.

``` r
cv_df = 
  crossv_mc(birthweight_dat, 100) %>% 
  mutate(
    train = map(train, as_tibble),
    test = map(test, as_tibble)
    ) %>% 
  mutate(model1  = map(train, ~lm( bwt ~ babysex + bhead + blength + delwt + fincome + gaweeks + mheight + mrace + parity + ppwt + smoken, data = .x)),
         model2  = map(train, ~lm(bwt ~ blength + gaweeks, data = .x)),
         model3  = map(train, ~lm(bwt ~ bhead * blength * babysex, data = .x))) %>% 
  mutate(rmse_model1 = map2_dbl(model1, test, ~rmse(model = .x, data = .y)),
         rmse_model2 = map2_dbl(model2, test, ~rmse(model = .x, data = .y)),
         rmse_model3 = map2_dbl(model3, test, ~rmse(model = .x, data = .y)))
```

``` r
cv_df %>% 
  select(starts_with("rmse")) %>% 
  pivot_longer(
    everything(),
    names_to = "model", 
    values_to = "rmse",
    names_prefix = "rmse_") %>% 
  mutate(model = fct_inorder(model)) %>% 
  ggplot(aes(x = model, y = rmse)) + geom_violin()
```

<img src="p8105_hw6_jc5314_files/figure-gfm/unnamed-chunk-8-1.png" width="90%" />

**Comment:** Based on the above plot, it can be seen that in
cross-validation model 1 had the lowest root-mean-square error and model
2 had the largest root-mean-square error. Therefore, we may say that
model 1 had the best performance among these three models while model 2
had the worst performance.

# Problem 2

Import data from website:

``` r
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
```

``` r
boot_straps = weather_df %>% 
  bootstrap(n = 5000) %>% 
  mutate(
    models = map(strap,~ lm(tmax ~ tmin, data = .x) ),
    results = map(models, broom::tidy),
    results_glance = map(models, broom::glance)) %>% 
  select(-strap, -models) %>% 
  unnest(results, results_glance) %>% 
  select(.id, term, estimate, r.squared) %>% 
  pivot_wider(
    names_from = "term",
    values_from = "estimate"
  ) %>% 
  janitor::clean_names() %>% 
  mutate(
    log_coef = log(intercept * tmin)
  )

boot_straps
```

    ## # A tibble: 5,000 x 5
    ##    id    r_squared intercept  tmin log_coef
    ##    <chr>     <dbl>     <dbl> <dbl>    <dbl>
    ##  1 0001      0.914      7.29  1.04     2.02
    ##  2 0002      0.917      6.73  1.07     1.97
    ##  3 0003      0.905      7.14  1.02     1.99
    ##  4 0004      0.902      7.59  1.02     2.05
    ##  5 0005      0.909      7.57  1.03     2.05
    ##  6 0006      0.910      7.10  1.04     2.00
    ##  7 0007      0.908      7.44  1.04     2.04
    ##  8 0008      0.907      7.75  1.01     2.06
    ##  9 0009      0.909      7.17  1.04     2.01
    ## 10 0010      0.895      7.86  1.01     2.07
    ## # … with 4,990 more rows

Plot of the distribution of
![\\hat{r}^2](https://latex.codecogs.com/png.latex?%5Chat%7Br%7D%5E2
"\\hat{r}^2"):

``` r
boot_straps %>% 
  ggplot(aes(x = r_squared)) +
  geom_density() +
  xlab("Estimated r squared")
```

<img src="p8105_hw6_jc5314_files/figure-gfm/unnamed-chunk-11-1.png" width="90%" />

**Comment:** Based on the plot, the
![\\hat{r}^2](https://latex.codecogs.com/png.latex?%5Chat%7Br%7D%5E2
"\\hat{r}^2") followed a normal distribution and had a well bell-shape
with a mean value around 0.91. It shows that the overvall values of
![\\hat{r}^2](https://latex.codecogs.com/png.latex?%5Chat%7Br%7D%5E2
"\\hat{r}^2") were high and the model had a good performance.

Plot of the distribution of
![log(\\hat{\\beta}\_0\*\\hat{\\beta}\_1)](https://latex.codecogs.com/png.latex?log%28%5Chat%7B%5Cbeta%7D_0%2A%5Chat%7B%5Cbeta%7D_1%29
"log(\\hat{\\beta}_0*\\hat{\\beta}_1)"):

``` r
boot_straps %>% 
  ggplot(aes(x = log_coef)) +
  geom_density() +
  xlab("Log(Beta_0 x Beta_1)")
```

<img src="p8105_hw6_jc5314_files/figure-gfm/unnamed-chunk-12-1.png" width="90%" />

**Comment:** Based on the plot, the
![log(\\hat{\\beta}\_0\*\\hat{\\beta}\_1)](https://latex.codecogs.com/png.latex?log%28%5Chat%7B%5Cbeta%7D_0%2A%5Chat%7B%5Cbeta%7D_1%29
"log(\\hat{\\beta}_0*\\hat{\\beta}_1)") also followed a normal
distribution and formed a bell-shape with a mean value around 2.01.

  - 2.5% and 97.5% quantiles for
    ![\\hat{r}^2](https://latex.codecogs.com/png.latex?%5Chat%7Br%7D%5E2
    "\\hat{r}^2"):

<!-- end list -->

``` r
ci_r = boot_straps %>% 
  pull(r_squared) %>% 
  quantile(c(0.025, 0.975))

ci_r
```

    ##      2.5%     97.5% 
    ## 0.8943272 0.9270342

The 95% confidence interval for
![\\hat{r}^2](https://latex.codecogs.com/png.latex?%5Chat%7Br%7D%5E2
"\\hat{r}^2") is (0.894, 0.927).

  - 2.5% and 97.5% quantiles for
    ![log(\\hat{\\beta}\_0\*\\hat{\\beta}\_1)](https://latex.codecogs.com/png.latex?log%28%5Chat%7B%5Cbeta%7D_0%2A%5Chat%7B%5Cbeta%7D_1%29
    "log(\\hat{\\beta}_0*\\hat{\\beta}_1)"):

<!-- end list -->

``` r
ci_log = boot_straps %>% 
  pull(log_coef) %>% 
  quantile(c(0.025, 0.975))

ci_log
```

    ##     2.5%    97.5% 
    ## 1.965135 2.058983

The 95% confidence interval for
![log(\\hat{\\beta}\_0\*\\hat{\\beta}\_1)](https://latex.codecogs.com/png.latex?log%28%5Chat%7B%5Cbeta%7D_0%2A%5Chat%7B%5Cbeta%7D_1%29
"log(\\hat{\\beta}_0*\\hat{\\beta}_1)") is (1.965, 2.059).
